### ISSUE TITLE
What does `sign_cert.key` corresponds to?

### ISSUE THREAD

**Issue by pixincreate** [chenxiaolong/my-avbroot-setup#1]
```
	--verify-public-key-avb verify_avb_pkmd.bin \
    --verify-cert-ota verify_ota.crt \
    --sign-key-avb sign_avb.key \
    --sign-key-ota sign_ota.key \
    --sign-cert-ota sign_cert.key \
```

Could you please elaborate on these please?

when I run:
```
avbroot key generate-key -o avb.key
avbroot key generate-key -o ota.key
avbroot key extract-avb -k avb.key -o avb_pkmd.bin
avbroot key generate-cert -k ota.key -o ota.crt
```

4 files are created and I believe they correspond to:
```
avb_pkmd.bin -> verify_avb_pkmd.bin
avb.key -> sign_avb.key
ota.key -> sign_ota.key
ota.crt -> verify_ota.crt
```
I'm unable to understand which file is `sign_cert.key`.

For ref: https://github.com/pixincreate/PixeneOS

**Comment by chenxiaolong** [comment]
Sure. `--sign-key-avb`, `--sign-key-ota`, and `--sign-cert-ota` correspond to your own keys. `avb_pkmd.bin` from your keys is not used.

`--verify-public-key-avb` and `--verify-cert-ota` are used to verify the original unmodified OTA. For example, if you downloaded an official GrapheneOS OTA, then you would pass in GrapheneOS' official AVB public key and OTA certificate.

**Comment by pixincreate** [comment]
So, for that, I need to extract the official OTA? Passing `avb_pkmd.bin` is useless? What should I pass to `--sign-cert-ota`?
Also, can the same be used to patch factory images?

**Comment by chenxiaolong** [comment]
I shouldn't have mentioned the official OTA since my script depends on userdebug builds, so I'm actually passing in the keys I used when I made my own GrapheneOS build.

But anyway, if you wanted to get the official AVB and OTA keys from an OTA, this is how you would do it:

* AVB: Extract `vbmeta.img`, run `avbroot avb info -i vbmeta.img`. The `public_key` field is `avb_pkmd.bin` encoded as hex. You can verify that the key is official by comparing its sha256 checksum with https://grapheneos.org/articles/attestation-compatibility-guide.
* OTA: Extract `META-INF/com/android/otacert` from the OTA. (Or from `otacerts.zip` inside `system.img` or `vendor_boot.img`. All 3 files are identical.)

> Also, can the same be used to patch factory images?

Nope, sorry. avbroot is completely incompatible with factory images.

**Comment by pixincreate** [comment]
I think i misunderstood somewhere around here.  
So, from what i understand, you build `user_debug` releases with your own signing keys. And patch the same with `my-avbroot-setup`, right?  

I've a few questions that are running in my mind currently:

- If I want to have `adbroot`, can I patch the existing build with `ro.adb.secure=1`? I believe no. Personally, I'm okay with that given my root use case
- Since `my-avbroot-setup` has almost everything that I need, I thought of using it for my own builds and did the necessary modifications. It is just that, I now need to `patch` the `ota`. i got confused when i saw 5 inputs while i had only 4
- Will try to fetch the official AVB and OTA keys. Again, this would still need me to have my own keys for signing if I'm not wrong. Will give it a shot tonight


> avbroot is completely incompatible with factory images.

My bad, yes, it is clearly mentioned as `ota`.

**Comment by chenxiaolong** [comment]
> So, from what i understand, you build `user_debug` releases with your own signing keys. And patch the same with `my-avbroot-setup`, right?  

Yep

> - If I want to have `adbroot`, can I patch the existing build with `ro.adb.secure=1`? I believe no. Personally, I'm okay with that given my root use case

For userdebug builds, `adb root` is always available, but the problem is that userdebug also turns off the normal adb authentication (where it prompts you whether to accept your computer's adb key). `ro.adb.secure=1` reenables that.

I add this property when building GrapheneOS, but it's possible to do this inside `my-avbroot-setup` too. Since `my-avbroot-setup` already extracts `system.img`, you can add a step that modifies `/system/build.prop` to change `ro.adb.secure=0` to `ro.adb.secure=1`.

> - Since `my-avbroot-setup` has almost everything that I need, I thought of using it for my own builds and did the necessary modifications. It is just that, I now need to `patch` the `ota`. i got confused when i saw 5 inputs while i had only 4
> - Will try to fetch the official AVB and OTA keys. Again, this would still need me to have my own keys for signing if I'm not wrong. Will give it a shot tonight

Yeah, the only purpose of `--verify-public-key-avb` and `--verify-cert-ota` is to verify that the input OTA is legitimate. They have no effect on the output. If this functionality isn't useful in your scenario, you could also remove it.

For me, I added it because I build GrapheneOS on a different machine than the one I run `my-avbroot-setup` on. I want to make sure the OTA I'm modifying is actually one that I built.

**Comment by pixincreate** [comment]
Got it. Thanks for this. I'll curate all these info in to a single doc and go through it before I proceed further with my changes. Closing the issue for now.

Thanks a lot agian!

**Comment by pixincreate** [comment]
<strike>
Hi there,

I had a lot of confusion previously until I went through the steps one by one.  

In the `patch.py`, first 2 inputs corresponds to the input OTA and you gave the steps to extract the keys [here](https://github.com/chenxiaolong/my-avbroot-setup/issues/1#issuecomment-2270286453). The question I have now is how can I use this?  

At the moment, this is what I've done:
</strike>
```sh
avbroot ota extract --input "${WORKDIR}/${GRAPHENEOS[OTA_TARGET]}.zip" --directory extracted/extracts --all

avbroot avb info -i extracted/extracts/vbmeta.img \
        | grep 'public_key' \
        | sed -n 's/.*public_key: "\(.*\)".*/\1/p' \
        | tr -d '[:space:]' | xxd -r -p > extracted/extracts/avb_pkmd.bin
sha256sum extracted/extracts/avb_pkmd_official_ota.bin # it does match with the ones mentioned in https://grapheneos.org/articles/attestation-compatibility-guide

unzip "${WORKDIR}/${GRAPHENEOS[OTA_TARGET]}.zip" -d extracted/ota
# pass the otacert and and avb_pkmd.bin to patch.py
```

<strike>Apologies if this is a dumb question.</strike> It was a dumb question, yes. Resolved.
